In [1]:
import requests as rq
import bs4
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'
page = rq.get(url, headers={"User-Agent": "Chrome"})
page.text[0 : 99]

'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-l'

In [3]:
bs4page = bs4.BeautifulSoup(page.text, 'html.parser')
tables = bs4page.find_all('table',{'class':"wikitable"})

In [4]:
gdp = pd.read_html(StringIO(str(tables[0])))[0]
with pd.option_context("display.max_rows", None): display(gdp)

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,126295331,118350166,111565144
1,United States,32383920,30769700,29298000
2,China[n 1],20851593,19498039,18743802
3,Germany,5452858,5050923,4659929
4,Japan,4379253,4435163,4026211
5,United Kingdom,4264794,4002588,3685881
6,India,4153191,3956067,3952244
7,France,3596094,3366316,3160443
8,Italy,2738164,2551557,2380825
9,Russia,2656452,2561310,2173386
10,Brazil,2635912,2279920,2185822
11,Canada,2507340,2319900,2270076
12,Australia,2123963,1798519,1830610
13,Mexico,2120855,1832641,1852723
14,Spain,2091222,1906453,1722746
15,South Korea,1931008,1872375,1875388
16,Turkey,1640223,1597293,1323255
17,Indonesia,1539872,1445643,1396300
18,Netherlands,1449704,1332768,1214928
19,Saudi Arabia,1388676,1276943,1254141
20,Switzerland,1146911,1043530,936564
21,Poland,1134248,1035492,914696
22,Taiwan[n 3],976719,—N/a,—N/a
23,Ireland,779381,721701,577389
24,Belgium,776730,725466,664564
25,Sweden,760481,668999,604899
26,Israel,719848,610778,542286
27,Argentina,688378,683098,638365
28,Singapore,659572,603870,547387
29,Austria,623719,579470,534791
30,United Arab Emirates,621546,"552,325 (2024)",552325
31,Norway,599406,530756,483593
32,Thailand,579996,577010,526518
33,Colombia,539530,457410,418542
34,Vietnam,527266,514697,476388
35,Malaysia,516428,472193,421972
36,Philippines,512222,487086,461618
37,Bangladesh,510705,456319,432742
38,Denmark,503772,462527,424525
39,Romania,480834,428678,382770
40,South Africa,479964,427184,401145
41,Hong Kong[n 4],450138,427310,406863
42,Czech Republic,432597,391027,345037
43,Egypt,429645,365255,306907
44,Chile,407850,357371,330267
45,Pakistan,"407,786 (2025)",407307,379120
46,Peru,380900,334855,289329
47,Portugal,380637,346640,313271
48,Nigeria,377365,290794,252084
49,Kazakhstan,360456,306239,291480
50,Finland,337669,317039,298697
51,Algeria,317173,287031,266972
52,Greece,307554,280636,257145
53,Iran,300293,362682,448092
54,New Zealand,278636,264057,260172
55,Hungary,271122,246490,222905
56,Iraq,264784,254367,279641
57,Cuba,—N/a,"107,352 (2020)",252063
58,Ukraine[n 5],225337,214233,190741
59,Qatar,217416,215560,219163
60,Morocco,194333,182374,160606
61,Uzbekistan,181502,147038,114965
62,Kuwait,172920,157209,160227
63,Slovakia,168897,154530,141776
64,Angola,152354,122175,117159
65,Bulgaria,148121,130777,113343
66,Kenya,147265,135941,120340
67,Ecuador,138194,130321,124676
68,Dominican Republic,136148,127407,124282
69,Puerto Rico,129012,129368,125842
70,Guatemala,128886,123306,113200
71,DR Congo,123406,91031,75322
72,Ethiopia,121527,126359,142275
73,Ghana,118293,114210,82938
74,Oman,117176,109605,107137
75,Croatia,116574,105060,92662
76,Ivory Coast,112115,99774,85894
77,Serbia,112025,99953,89074
78,Venezuela,111303,99661,150494
79,Luxembourg,110417,101158,93280
80,Costa Rica,109931,102905,95350
81,Sri Lanka,"98,964 (2024)",108825,98714
82,Lithuania,105907,95210,84869
83,Belarus,102042,93397,75962
84,Uruguay,96092,85348,80962
85,Panama,95024,90463,86260
86,Tanzania[n 6],94889,90143,79236
87,Slovenia,86732,79648,72485
88,Myanmar,83832,81666,64796
89,Turkmenistan,83065,49829,68655
90,Bolivia,80743,64769,46627
91,Azerbaijan,78372,75938,74316
92,Uganda,73370,61986,56369
93,Cameroon,65135,58933,53297
94,Jordan,64909,61610,53352
95,Tunisia,60745,57503,53493
96,Paraguay,60542,49278,44739
97,Zimbabwe,56713,51216,45719
98,Macau[n 7],54228,52061,49467
99,Latvia,53686,48619,43684
100,Libya,52453,48099,48484
101,Cambodia,52379,51267,45913
102,Estonia,51634,47031,42765
103,Bahrain,48849,48966,47110
104,Nepal,45844,45490,42692
105,Cyprus[n 8],45171,41226,37635
106,Sudan,44688,60163,25574
107,Iceland,43800,38583,33222
108,Georgia[n 9],42716,38144,34192
109,Honduras,41505,39601,37094
110,Zambia,41243,28880,25303
111,Senegal,40469,37007,36715
112,El Salvador,39838,36708,35365
113,Haiti,39180,32077,25312
114,Bosnia and Herzegovina,36771,32600,30478
115,Lebanon,"34,497 (2025)","25,972 (2024)",37990
116,Papua New Guinea,34403,32499,32262
117,Guyana,33961,27097,24659
118,Mali,33847,30069,26588
119,Albania,33333,30540,27037
120,Burkina Faso,32513,27627,23250
121,Armenia,31873,29243,25955
122,Malta,30712,27772,25030
123,Guinea,29930,28346,36465
124,Mongolia,28450,25369,23586
125,Benin,27786,24566,21483
126,Trinidad and Tobago,26836,25943,25634
127,Chad,25628,21473,19906
128,Niger,24813,21646,17491
129,Nicaragua,24227,22237,19694
130,Kyrgyzstan,23606,22624,17478
131,Gabon,23363,21427,20867
132,Mozambique,23275,22338,22745
133,Jamaica,23028,22705,22014
134,Botswana,21937,19928,19401
135,Moldova[n 10],21889,20352,18200
136,North Macedonia,21605,19101,16952
137,Madagascar,21185,19620,17421
138,Tajikistan,20418,17661,13949
139,Afghanistan,"19,662 (2025)","17,779 (2024)",18283
140,Laos,18959,18303,16129
141,Malawi,18152,14918,11734
142,Rwanda,17336,16372,15111
143,Namibia,17314,15080,13372
144,Syria,"60,043 (2010)","23,738 (2022)",17254
145,North Korea,—N/a,—N/a,17199
146,Palestine[n 11][n 12],"16,017 (2024)",17167,16017
147,Mauritius,17119,16158,14953
148,Bahamas,17042,"15,833 (2024)",15833
149,Congo,17028,16307,16412
150,Brunei,16863,15032,15463
151,Mauritania,14352,11680,10912
152,Somalia,14174,12995,11966
153,Kosovo,14053,12456,11154
154,Equatorial Guinea,13722,12823,12288
155,Togo,13437,11890,10163
156,Channel Islands,—N/a,"12,507 (2023)",—N/a
157,Monaco,—N/a,"11,126 (2024)",11126
158,Montenegro,10227,9233,8274
159,Liechtenstein,9442,"8,906 (2024)",8628
160,Bermuda,—N/a,"9,194 (2024)",8840
161,New Caledonia,—N/a,"8,549 (2024)",8549
162,Barbados,8483,8017,7598
163,Sierra Leone,8270,7464,6792
164,Burundi,8137,3365,4431
165,Maldives,8130,7741,7062
166,Cayman Islands,—N/a,"7,765 (2024)",7657
167,Isle of Man,—N/a,"7,576 (2023)",—N/a
168,Yemen,7435,"21,606 (2018)",14304
169,Guam,—N/a,"6,910 (2022)",—N/a
170,Fiji,6352,6198,5968
171,French Polynesia,—N/a,"6,324 (2024)",6323
172,South Sudan,6069,"11,998 (2015)",3522
173,Suriname,5908,4524,4435
174,Eswatini,5792,5161,4947
175,Liberia,5642,5246,5251
176,Andorra,4879,4501,4040
177,Djibouti,4725,4625,4152
178,U.S. Virgin Islands,—N/a,"4,672 (2022)",—N/a
179,Aruba,4671,"4,168 (2024)",4192
180,Faroe Islands,—N/a,"4,053 (2024)",—N/a
181,Bhutan,3856,3579,3347
182,Curaçao,—N/a,"3,561 (2024)",3561
183,Central African Republic,3492,3066,2752
184,Greenland,—N/a,"3,327 (2023)",3466
185,Belize,3450,3327,3204
186,Cape Verde,3448,3057,2768
187,Guinea-Bissau,2985,2528,2008
188,Lesotho,2972,2574,2391
189,Gambia,2792,2594,2372
190,Saint Lucia,2765,2656,2574
191,Zanzibar,—N/a,—N/a,2530
192,San Marino,2417,"2,027 (2023)",2082
193,Antigua and Barbuda,2385,2338,2162
194,Seychelles,2251,2387,2162
195,Timor-Leste,2170,1902,1866
196,Eritrea,"1,982 (2019)","2,065 (2011)",1917
197,Sint Maarten,—N/a,1888,1670
198,Solomon Islands,1836,1750,1584
199,British Virgin Islands,—N/a,—N/a,1830
200,Comoros,1814,1815,1567
201,Turks and Caicos Islands,—N/a,"1,745 (2024)",1757
202,Grenada,1483,1420,1372
203,Vanuatu,1396,1354,1092
204,Samoa,1376,1288,1253
205,Saint Vincent and the Grenadines,1236,1255,1136
206,São Tomé and Príncipe,1161,981,828
207,Saint Kitts and Nevis,1143,1184,1122
208,Northern Mariana Islands,—N/a,"1,096 (2022)",—N/a
209,American Samoa,—N/a,871 (2022),—N/a
210,Dominica,791,724,689
211,Tonga,716,679,648
212,Saint Martin,—N/a,649 (2021),—N/a
213,Federated States of Micronesia,521,502,471
214,Anguilla,—N/a,—N/a,456
215,Cook Islands,—N/a,—N/a,414
216,Kiribati,401,349,343
217,Palau,377,345,310
218,Marshall Islands,342,308,281
219,Nauru,196,176,187
220,Montserrat,—N/a,—N/a,81
221,Tuvalu,65,57,56

In [10]:
url = 'https://en.wikipedia.org/w/index.php?title=List_of_countries_by_GDP_(nominal)&oldid=1187446467'
page = rq.get(url, headers={"User-Agent": "Chrome"})

bs4page = bs4.BeautifulSoup(page.text, 'html.parser')
table = bs4page.find("caption", string="GDP (USD million) by country").find_parent("table")

data = []
for row in table.find_all("tr"):
    cells = row.find_all("td")
    if len(cells) != 8: continue
    values = [cell.get_text(" ", strip=True) for cell in cells]
    data.append({"Country": values[0], "Region": values[1],})

regions = pd.DataFrame(data)
with pd.option_context("display.max_rows", None): display(regions)

                              Country    Region
0                               World         —
1                       United States  Americas
2                               China      Asia
3                             Germany    Europe
4                               Japan      Asia
5                               India      Asia
6                      United Kingdom    Europe
7                              France    Europe
8                               Italy    Europe
9                              Brazil  Americas
10                             Canada  Americas
11                             Russia    Europe
12                             Mexico  Americas
13                        South Korea      Asia
14                          Australia   Oceania
15                              Spain    Europe
16                          Indonesia      Asia
17                             Turkey      Asia
18                        Netherlands    Europe
19                       Saudi Arabia      Asia
20                        Switzerland    Europe
21                             Poland    Europe
22                            Belgium    Europe
23                          Argentina  Americas
24                             Sweden    Europe
25                            Ireland    Europe
26                             Norway    Europe
27                            Austria    Europe
28                             Israel      Asia
29                           Thailand      Asia
30               United Arab Emirates      Asia
31                          Singapore      Asia
32                         Bangladesh      Asia
33                        Philippines      Asia
34                            Vietnam      Asia
35                           Malaysia      Asia
36                            Denmark    Europe
37                              Egypt    Africa
38                            Nigeria    Africa
39                          Hong Kong      Asia
40                       South Africa    Africa
41                               Iran      Asia
42                           Colombia  Americas
43                            Romania    Europe
44                              Chile  Americas
45                           Pakistan      Asia
46                     Czech Republic    Europe
47                            Finland    Europe
48                               Iraq      Asia
49                           Portugal    Europe
50                               Peru  Americas
51                         Kazakhstan      Asia
52                        New Zealand   Oceania
53                             Greece    Europe
54                              Qatar      Asia
55                            Algeria    Africa
56                            Hungary    Europe
57                            Ukraine    Europe
58                             Kuwait      Asia
59                           Ethiopia    Africa
60                            Morocco    Africa
61                           Slovakia    Europe
62                 Dominican Republic  Americas
63                            Ecuador  Americas
64                        Puerto Rico  Americas
65                              Kenya    Africa
66                               Oman      Asia
67                           Bulgaria    Europe
68                          Guatemala  Americas
69                             Angola    Africa
70                         Uzbekistan      Asia
71                         Luxembourg    Europe
72                         Costa Rica  Americas
73                           Tanzania    Africa
74                             Panama  Americas
75                            Croatia    Europe
76                        Ivory Coast    Africa
77                          Lithuania    Europe
78                         Azerbaijan      Asia
79                              Ghana    Africa
80                            Uruguay  Americas
81                             Serbia    Europe
82                            Myanmar      Asia
83                            Belarus    Europe
84                           Slovenia    Europe
85                           DR Congo    Africa
86                             Uganda    Africa
87                            Tunisia    Africa
88                             Jordan      Asia
89                           Cameroon    Africa
90                            Bolivia  Americas
91                             Latvia    Europe
92                            Bahrain      Asia
93                           Paraguay  Americas
94                            Estonia    Europe
95                              Nepal      Asia
96                              Libya    Africa
97                              Macau      Asia
98                        El Salvador  Americas
99                           Honduras  Americas
100                          Zimbabwe    Africa
101                            Cyprus      Asia
102                  Papua New Guinea   Oceania
103                           Senegal    Africa
104                          Cambodia      Asia
105                           Iceland    Europe
106                           Georgia      Asia
107                            Zambia    Africa
108               Trinidad and Tobago  Americas
109            Bosnia and Herzegovina    Europe
110                             Haiti  Americas
111                             Sudan    Africa
112                           Armenia      Asia
113                            Guinea    Africa
114                           Albania    Europe
115                        Mozambique    Africa
116                              Mali    Africa
117                      Burkina Faso    Africa
118                          Botswana    Africa
119                             Malta    Europe
120                             Benin    Africa
121                             Gabon    Africa
122                         Palestine      Asia
123                          Mongolia      Asia
124                           Jamaica  Americas
125                         Nicaragua  Americas
126                             Niger    Africa
127                            Guyana  Americas
128                           Moldova    Europe
129                   North Macedonia    Europe
130                        Madagascar    Africa
131                            Brunei      Asia
132                         Mauritius    Africa
133                             Congo    Africa
134                              Laos      Asia
135                            Rwanda    Africa
136                           Bahamas  Americas
137                            Malawi    Africa
138                        Kyrgyzstan      Asia
139                           Namibia    Africa
140                              Chad    Africa
141                        Tajikistan      Asia
142                           Somalia    Africa
143                            Kosovo    Europe
144                        Mauritania    Africa
145                 Equatorial Guinea    Africa
146                              Togo    Africa
147                        Montenegro    Europe
148                          Maldives      Asia
149                          Barbados  Americas
150                              Fiji   Oceania
151                          Eswatini    Africa
152                           Liberia    Africa
153                          Djibouti    Africa
154                           Andorra    Europe
155                          Suriname  Americas
156                      Sierra Leone    Africa
157                            Belize  Americas
158                           Burundi    Africa
159          Central African Republic    Africa
160                        Cape Verde    Africa
161                       Saint Lucia  Americas
162                            Gambia    Africa
163                           Lesotho    Africa
164                        Seychelles    Africa
165                       Timor-Leste      Asia
166                     Guinea-Bissau    Africa
167               Antigua and Barbuda  Americas
168                   Solomon Islands   Oceania
169                           Comoros    Africa
170                           Grenada  Americas
171                           Vanuatu   Oceania
172             Saint Kitts and Nevis  Americas
173  Saint Vincent and the Grenadines  Americas
174                             Samoa   Oceania
175                          Dominica  Americas
176             São Tomé and Príncipe    Africa
177    Federated States of Micronesia   Oceania
178                  Marshall Islands   Oceania
179                          Kiribati   Oceania
180                             Nauru   Oceania
181                            Tuvalu   Oceania

In [11]:
gdp["Country/Territory"] = (gdp["Country/Territory"].str.replace(r"\[.*?\]", "", regex=True).str.strip())
regions["Country"] = (regions["Country"].str.replace(r"\[.*?\]", "", regex=True).str.strip())
df = (gdp.merge(regions, left_on="Country/Territory",right_on="Country",how="left").drop(columns="Country"))
with pd.option_context("display.max_rows", None): display(df)

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7],Region
0,World,126295331,118350166,111565144,—
1,United States,32383920,30769700,29298000,Americas
2,China,20851593,19498039,18743802,Asia
3,Germany,5452858,5050923,4659929,Europe
4,Japan,4379253,4435163,4026211,Asia
5,United Kingdom,4264794,4002588,3685881,Europe
6,India,4153191,3956067,3952244,Asia
7,France,3596094,3366316,3160443,Europe
8,Italy,2738164,2551557,2380825,Europe
9,Russia,2656452,2561310,2173386,Europe
10,Brazil,2635912,2279920,2185822,Americas
11,Canada,2507340,2319900,2270076,Americas
12,Australia,2123963,1798519,1830610,Oceania
13,Mexico,2120855,1832641,1852723,Americas
14,Spain,2091222,1906453,1722746,Europe
15,South Korea,1931008,1872375,1875388,Asia
16,Turkey,1640223,1597293,1323255,Asia
17,Indonesia,1539872,1445643,1396300,Asia
18,Netherlands,1449704,1332768,1214928,Europe
19,Saudi Arabia,1388676,1276943,1254141,Asia
20,Switzerland,1146911,1043530,936564,Europe
21,Poland,1134248,1035492,914696,Europe
22,Taiwan,976719,—N/a,—N/a,NaN
23,Ireland,779381,721701,577389,Europe
24,Belgium,776730,725466,664564,Europe
25,Sweden,760481,668999,604899,Europe
26,Israel,719848,610778,542286,Asia
27,Argentina,688378,683098,638365,Americas
28,Singapore,659572,603870,547387,Asia
29,Austria,623719,579470,534791,Europe
30,United Arab Emirates,621546,"552,325 (2024)",552325,Asia
31,Norway,599406,530756,483593,Europe
32,Thailand,579996,577010,526518,Asia
33,Colombia,539530,457410,418542,Americas
34,Vietnam,527266,514697,476388,Asia
35,Malaysia,516428,472193,421972,Asia
36,Philippines,512222,487086,461618,Asia
37,Bangladesh,510705,456319,432742,Asia
38,Denmark,503772,462527,424525,Europe
39,Romania,480834,428678,382770,Europe
40,South Africa,479964,427184,401145,Africa
41,Hong Kong,450138,427310,406863,Asia
42,Czech Republic,432597,391027,345037,Europe
43,Egypt,429645,365255,306907,Africa
44,Chile,407850,357371,330267,Americas
45,Pakistan,"407,786 (2025)",407307,379120,Asia
46,Peru,380900,334855,289329,Americas
47,Portugal,380637,346640,313271,Europe
48,Nigeria,377365,290794,252084,Africa
49,Kazakhstan,360456,306239,291480,Asia
50,Finland,337669,317039,298697,Europe
51,Algeria,317173,287031,266972,Africa
52,Greece,307554,280636,257145,Europe
53,Iran,300293,362682,448092,Asia
54,New Zealand,278636,264057,260172,Oceania
55,Hungary,271122,246490,222905,Europe
56,Iraq,264784,254367,279641,Asia
57,Cuba,—N/a,"107,352 (2020)",252063,NaN
58,Ukraine,225337,214233,190741,Europe
59,Qatar,217416,215560,219163,Asia
60,Morocco,194333,182374,160606,Africa
61,Uzbekistan,181502,147038,114965,Asia
62,Kuwait,172920,157209,160227,Asia
63,Slovakia,168897,154530,141776,Europe
64,Angola,152354,122175,117159,Africa
65,Bulgaria,148121,130777,113343,Europe
66,Kenya,147265,135941,120340,Africa
67,Ecuador,138194,130321,124676,Americas
68,Dominican Republic,136148,127407,124282,Americas
69,Puerto Rico,129012,129368,125842,Americas
70,Guatemala,128886,123306,113200,Americas
71,DR Congo,123406,91031,75322,Africa
72,Ethiopia,121527,126359,142275,Africa
73,Ghana,118293,114210,82938,Africa
74,Oman,117176,109605,107137,Asia
75,Croatia,116574,105060,92662,Europe
76,Ivory Coast,112115,99774,85894,Africa
77,Serbia,112025,99953,89074,Europe
78,Venezuela,111303,99661,150494,NaN
79,Luxembourg,110417,101158,93280,Europe
80,Costa Rica,109931,102905,95350,Americas
81,Sri Lanka,"98,964 (2024)",108825,98714,NaN
82,Lithuania,105907,95210,84869,Europe
83,Belarus,102042,93397,75962,Europe
84,Uruguay,96092,85348,80962,Americas
85,Panama,95024,90463,86260,Americas
86,Tanzania,94889,90143,79236,Africa
87,Slovenia,86732,79648,72485,Europe
88,Myanmar,83832,81666,64796,Asia
89,Turkmenistan,83065,49829,68655,NaN
90,Bolivia,80743,64769,46627,Americas
91,Azerbaijan,78372,75938,74316,Asia
92,Uganda,73370,61986,56369,Africa
93,Cameroon,65135,58933,53297,Africa
94,Jordan,64909,61610,53352,Asia
95,Tunisia,60745,57503,53493,Africa
96,Paraguay,60542,49278,44739,Americas
97,Zimbabwe,56713,51216,45719,Africa
98,Macau,54228,52061,49467,Asia
99,Latvia,53686,48619,43684,Europe
100,Libya,52453,48099,48484,Africa
101,Cambodia,52379,51267,45913,Asia
102,Estonia,51634,47031,42765,Europe
103,Bahrain,48849,48966,47110,Asia
104,Nepal,45844,45490,42692,Asia
105,Cyprus,45171,41226,37635,Asia
106,Sudan,44688,60163,25574,Africa
107,Iceland,43800,38583,33222,Europe
108,Georgia,42716,38144,34192,Asia
109,Honduras,41505,39601,37094,Americas
110,Zambia,41243,28880,25303,Africa
111,Senegal,40469,37007,36715,Africa
112,El Salvador,39838,36708,35365,Americas
113,Haiti,39180,32077,25312,Americas
114,Bosnia and Herzegovina,36771,32600,30478,Europe
115,Lebanon,"34,497 (2025)","25,972 (2024)",37990,NaN
116,Papua New Guinea,34403,32499,32262,Oceania
117,Guyana,33961,27097,24659,Americas
118,Mali,33847,30069,26588,Africa
119,Albania,33333,30540,27037,Europe
120,Burkina Faso,32513,27627,23250,Africa
121,Armenia,31873,29243,25955,Asia
122,Malta,30712,27772,25030,Europe
123,Guinea,29930,28346,36465,Africa
124,Mongolia,28450,25369,23586,Asia
125,Benin,27786,24566,21483,Africa
126,Trinidad and Tobago,26836,25943,25634,Americas
127,Chad,25628,21473,19906,Africa
128,Niger,24813,21646,17491,Africa
129,Nicaragua,24227,22237,19694,Americas
130,Kyrgyzstan,23606,22624,17478,Asia
131,Gabon,23363,21427,20867,Africa
132,Mozambique,23275,22338,22745,Africa
133,Jamaica,23028,22705,22014,Americas
134,Botswana,21937,19928,19401,Africa
135,Moldova,21889,20352,18200,Europe
136,North Macedonia,21605,19101,16952,Europe
137,Madagascar,21185,19620,17421,Africa
138,Tajikistan,20418,17661,13949,Asia
139,Afghanistan,"19,662 (2025)","17,779 (2024)",18283,NaN
140,Laos,18959,18303,16129,Asia
141,Malawi,18152,14918,11734,Africa
142,Rwanda,17336,16372,15111,Africa
143,Namibia,17314,15080,13372,Africa
144,Syria,"60,043 (2010)","23,738 (2022)",17254,NaN
145,North Korea,—N/a,—N/a,17199,NaN
146,Palestine,"16,017 (2024)",17167,16017,Asia
147,Mauritius,17119,16158,14953,Africa
148,Bahamas,17042,"15,833 (2024)",15833,Americas
149,Congo,17028,16307,16412,Africa
150,Brunei,16863,15032,15463,Asia
151,Mauritania,14352,11680,10912,Africa
152,Somalia,14174,12995,11966,Africa
153,Kosovo,14053,12456,11154,Europe
154,Equatorial Guinea,13722,12823,12288,Africa
155,Togo,13437,11890,10163,Africa
156,Channel Islands,—N/a,"12,507 (2023)",—N/a,NaN
157,Monaco,—N/a,"11,126 (2024)",11126,NaN
158,Montenegro,10227,9233,8274,Europe
159,Liechtenstein,9442,"8,906 (2024)",8628,NaN
160,Bermuda,—N/a,"9,194 (2024)",8840,NaN
161,New Caledonia,—N/a,"8,549 (2024)",8549,NaN
162,Barbados,8483,8017,7598,Americas
163,Sierra Leone,8270,7464,6792,Africa
164,Burundi,8137,3365,4431,Africa
165,Maldives,8130,7741,7062,Asia
166,Cayman Islands,—N/a,"7,765 (2024)",7657,NaN
167,Isle of Man,—N/a,"7,576 (2023)",—N/a,NaN
168,Yemen,7435,"21,606 (2018)",14304,NaN
169,Guam,—N/a,"6,910 (2022)",—N/a,NaN
170,Fiji,6352,6198,5968,Oceania
171,French Polynesia,—N/a,"6,324 (2024)",6323,NaN
172,South Sudan,6069,"11,998 (2015)",3522,NaN
173,Suriname,5908,4524,4435,Americas
174,Eswatini,5792,5161,4947,Africa
175,Liberia,5642,5246,5251,Africa
176,Andorra,4879,4501,4040,Europe
177,Djibouti,4725,4625,4152,Africa
178,U.S. Virgin Islands,—N/a,"4,672 (2022)",—N/a,NaN
179,Aruba,4671,"4,168 (2024)",4192,NaN
180,Faroe Islands,—N/a,"4,053 (2024)",—N/a,NaN
181,Bhutan,3856,3579,3347,NaN
182,Curaçao,—N/a,"3,561 (2024)",3561,NaN
183,Central African Republic,3492,3066,2752,Africa
184,Greenland,—N/a,"3,327 (2023)",3466,NaN
185,Belize,3450,3327,3204,Americas
186,Cape Verde,3448,3057,2768,Africa
187,Guinea-Bissau,2985,2528,2008,Africa
188,Lesotho,2972,2574,2391,Africa
189,Gambia,2792,2594,2372,Africa
190,Saint Lucia,2765,2656,2574,Americas
191,Zanzibar,—N/a,—N/a,2530,NaN
192,San Marino,2417,"2,027 (2023)",2082,NaN
193,Antigua and Barbuda,2385,2338,2162,Americas
194,Seychelles,2251,2387,2162,Africa
195,Timor-Leste,2170,1902,1866,Asia
196,Eritrea,"1,982 (2019)","2,065 (2011)",1917,NaN
197,Sint Maarten,—N/a,1888,1670,NaN
198,Solomon Islands,1836,1750,1584,Oceania
199,British Virgin Islands,—N/a,—N/a,1830,NaN
200,Comoros,1814,1815,1567,Africa
201,Turks and Caicos Islands,—N/a,"1,745 (2024)",1757,NaN
202,Grenada,1483,1420,1372,Americas
203,Vanuatu,1396,1354,1092,Oceania
204,Samoa,1376,1288,1253,Oceania
205,Saint Vincent and the Grenadines,1236,1255,1136,Americas
206,São Tomé and Príncipe,1161,981,828,Africa
207,Saint Kitts and Nevis,1143,1184,1122,Americas
208,Northern Mariana Islands,—N/a,"1,096 (2022)",—N/a,NaN
209,American Samoa,—N/a,871 (2022),—N/a,NaN
210,Dominica,791,724,689,Americas
211,Tonga,716,679,648,NaN
212,Saint Martin,—N/a,649 (2021),—N/a,NaN
213,Federated States of Micronesia,521,502,471,Oceania
214,Anguilla,—N/a,—N/a,456,NaN
215,Cook Islands,—N/a,—N/a,414,NaN
216,Kiribati,401,349,343,Oceania
217,Palau,377,345,310,NaN
218,Marshall Islands,342,308,281,Oceania
219,Nauru,196,176,187,Oceania
220,Montserrat,—N/a,—N/a,81,NaN
221,Tuvalu,65,57,56,Oceania

In [12]:
df = df.replace(["—N/a", "NaN"], np.nan)
df["GDP"] = (df["IMF (2026)[1]"].fillna(df["World Bank (2025)[6]"]).fillna(df["United Nations (2024)[7]"]))
df["GDP"] = (df["GDP"].astype(str).str.replace(r"\s*\(\d{4}\)", "", regex=True))
with pd.option_context("display.max_rows", None): display(df)

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7],Region,GDP
0,World,126295331,118350166,111565144,—,126295331
1,United States,32383920,30769700,29298000,Americas,32383920
2,China,20851593,19498039,18743802,Asia,20851593
3,Germany,5452858,5050923,4659929,Europe,5452858
4,Japan,4379253,4435163,4026211,Asia,4379253
5,United Kingdom,4264794,4002588,3685881,Europe,4264794
6,India,4153191,3956067,3952244,Asia,4153191
7,France,3596094,3366316,3160443,Europe,3596094
8,Italy,2738164,2551557,2380825,Europe,2738164
9,Russia,2656452,2561310,2173386,Europe,2656452
10,Brazil,2635912,2279920,2185822,Americas,2635912
11,Canada,2507340,2319900,2270076,Americas,2507340
12,Australia,2123963,1798519,1830610,Oceania,2123963
13,Mexico,2120855,1832641,1852723,Americas,2120855
14,Spain,2091222,1906453,1722746,Europe,2091222
15,South Korea,1931008,1872375,1875388,Asia,1931008
16,Turkey,1640223,1597293,1323255,Asia,1640223
17,Indonesia,1539872,1445643,1396300,Asia,1539872
18,Netherlands,1449704,1332768,1214928,Europe,1449704
19,Saudi Arabia,1388676,1276943,1254141,Asia,1388676
20,Switzerland,1146911,1043530,936564,Europe,1146911
21,Poland,1134248,1035492,914696,Europe,1134248
22,Taiwan,976719,NaN,NaN,NaN,976719
23,Ireland,779381,721701,577389,Europe,779381
24,Belgium,776730,725466,664564,Europe,776730
25,Sweden,760481,668999,604899,Europe,760481
26,Israel,719848,610778,542286,Asia,719848
27,Argentina,688378,683098,638365,Americas,688378
28,Singapore,659572,603870,547387,Asia,659572
29,Austria,623719,579470,534791,Europe,623719
30,United Arab Emirates,621546,"552,325 (2024)",552325,Asia,621546
31,Norway,599406,530756,483593,Europe,599406
32,Thailand,579996,577010,526518,Asia,579996
33,Colombia,539530,457410,418542,Americas,539530
34,Vietnam,527266,514697,476388,Asia,527266
35,Malaysia,516428,472193,421972,Asia,516428
36,Philippines,512222,487086,461618,Asia,512222
37,Bangladesh,510705,456319,432742,Asia,510705
38,Denmark,503772,462527,424525,Europe,503772
39,Romania,480834,428678,382770,Europe,480834
40,South Africa,479964,427184,401145,Africa,479964
41,Hong Kong,450138,427310,406863,Asia,450138
42,Czech Republic,432597,391027,345037,Europe,432597
43,Egypt,429645,365255,306907,Africa,429645
44,Chile,407850,357371,330267,Americas,407850
45,Pakistan,"407,786 (2025)",407307,379120,Asia,"407,786"
46,Peru,380900,334855,289329,Americas,380900
47,Portugal,380637,346640,313271,Europe,380637
48,Nigeria,377365,290794,252084,Africa,377365
49,Kazakhstan,360456,306239,291480,Asia,360456
50,Finland,337669,317039,298697,Europe,337669
51,Algeria,317173,287031,266972,Africa,317173
52,Greece,307554,280636,257145,Europe,307554
53,Iran,300293,362682,448092,Asia,300293
54,New Zealand,278636,264057,260172,Oceania,278636
55,Hungary,271122,246490,222905,Europe,271122
56,Iraq,264784,254367,279641,Asia,264784
57,Cuba,NaN,"107,352 (2020)",252063,NaN,"107,352"
58,Ukraine,225337,214233,190741,Europe,225337
59,Qatar,217416,215560,219163,Asia,217416
60,Morocco,194333,182374,160606,Africa,194333
61,Uzbekistan,181502,147038,114965,Asia,181502
62,Kuwait,172920,157209,160227,Asia,172920
63,Slovakia,168897,154530,141776,Europe,168897
64,Angola,152354,122175,117159,Africa,152354
65,Bulgaria,148121,130777,113343,Europe,148121
66,Kenya,147265,135941,120340,Africa,147265
67,Ecuador,138194,130321,124676,Americas,138194
68,Dominican Republic,136148,127407,124282,Americas,136148
69,Puerto Rico,129012,129368,125842,Americas,129012
70,Guatemala,128886,123306,113200,Americas,128886
71,DR Congo,123406,91031,75322,Africa,123406
72,Ethiopia,121527,126359,142275,Africa,121527
73,Ghana,118293,114210,82938,Africa,118293
74,Oman,117176,109605,107137,Asia,117176
75,Croatia,116574,105060,92662,Europe,116574
76,Ivory Coast,112115,99774,85894,Africa,112115
77,Serbia,112025,99953,89074,Europe,112025
78,Venezuela,111303,99661,150494,NaN,111303
79,Luxembourg,110417,101158,93280,Europe,110417
80,Costa Rica,109931,102905,95350,Americas,109931
81,Sri Lanka,"98,964 (2024)",108825,98714,NaN,"98,964"
82,Lithuania,105907,95210,84869,Europe,105907
83,Belarus,102042,93397,75962,Europe,102042
84,Uruguay,96092,85348,80962,Americas,96092
85,Panama,95024,90463,86260,Americas,95024
86,Tanzania,94889,90143,79236,Africa,94889
87,Slovenia,86732,79648,72485,Europe,86732
88,Myanmar,83832,81666,64796,Asia,83832
89,Turkmenistan,83065,49829,68655,NaN,83065
90,Bolivia,80743,64769,46627,Americas,80743
91,Azerbaijan,78372,75938,74316,Asia,78372
92,Uganda,73370,61986,56369,Africa,73370
93,Cameroon,65135,58933,53297,Africa,65135
94,Jordan,64909,61610,53352,Asia,64909
95,Tunisia,60745,57503,53493,Africa,60745
96,Paraguay,60542,49278,44739,Americas,60542
97,Zimbabwe,56713,51216,45719,Africa,56713
98,Macau,54228,52061,49467,Asia,54228
99,Latvia,53686,48619,43684,Europe,53686
100,Libya,52453,48099,48484,Africa,52453
101,Cambodia,52379,51267,45913,Asia,52379
102,Estonia,51634,47031,42765,Europe,51634
103,Bahrain,48849,48966,47110,Asia,48849
104,Nepal,45844,45490,42692,Asia,45844
105,Cyprus,45171,41226,37635,Asia,45171
106,Sudan,44688,60163,25574,Africa,44688
107,Iceland,43800,38583,33222,Europe,43800
108,Georgia,42716,38144,34192,Asia,42716
109,Honduras,41505,39601,37094,Americas,41505
110,Zambia,41243,28880,25303,Africa,41243
111,Senegal,40469,37007,36715,Africa,40469
112,El Salvador,39838,36708,35365,Americas,39838
113,Haiti,39180,32077,25312,Americas,39180
114,Bosnia and Herzegovina,36771,32600,30478,Europe,36771
115,Lebanon,"34,497 (2025)","25,972 (2024)",37990,NaN,"34,497"
116,Papua New Guinea,34403,32499,32262,Oceania,34403
117,Guyana,33961,27097,24659,Americas,33961
118,Mali,33847,30069,26588,Africa,33847
119,Albania,33333,30540,27037,Europe,33333
120,Burkina Faso,32513,27627,23250,Africa,32513
121,Armenia,31873,29243,25955,Asia,31873
122,Malta,30712,27772,25030,Europe,30712
123,Guinea,29930,28346,36465,Africa,29930
124,Mongolia,28450,25369,23586,Asia,28450
125,Benin,27786,24566,21483,Africa,27786
126,Trinidad and Tobago,26836,25943,25634,Americas,26836
127,Chad,25628,21473,19906,Africa,25628
128,Niger,24813,21646,17491,Africa,24813
129,Nicaragua,24227,22237,19694,Americas,24227
130,Kyrgyzstan,23606,22624,17478,Asia,23606
131,Gabon,23363,21427,20867,Africa,23363
132,Mozambique,23275,22338,22745,Africa,23275
133,Jamaica,23028,22705,22014,Americas,23028
134,Botswana,21937,19928,19401,Africa,21937
135,Moldova,21889,20352,18200,Europe,21889
136,North Macedonia,21605,19101,16952,Europe,21605
137,Madagascar,21185,19620,17421,Africa,21185
138,Tajikistan,20418,17661,13949,Asia,20418
139,Afghanistan,"19,662 (2025)","17,779 (2024)",18283,NaN,"19,662"
140,Laos,18959,18303,16129,Asia,18959
141,Malawi,18152,14918,11734,Africa,18152
142,Rwanda,17336,16372,15111,Africa,17336
143,Namibia,17314,15080,13372,Africa,17314
144,Syria,"60,043 (2010)","23,738 (2022)",17254,NaN,"60,043"
145,North Korea,NaN,NaN,17199,NaN,17199
146,Palestine,"16,017 (2024)",17167,16017,Asia,"16,017"
147,Mauritius,17119,16158,14953,Africa,17119
148,Bahamas,17042,"15,833 (2024)",15833,Americas,17042
149,Congo,17028,16307,16412,Africa,17028
150,Brunei,16863,15032,15463,Asia,16863
151,Mauritania,14352,11680,10912,Africa,14352
152,Somalia,14174,12995,11966,Africa,14174
153,Kosovo,14053,12456,11154,Europe,14053
154,Equatorial Guinea,13722,12823,12288,Africa,13722
155,Togo,13437,11890,10163,Africa,13437
156,Channel Islands,NaN,"12,507 (2023)",NaN,NaN,"12,507"
157,Monaco,NaN,"11,126 (2024)",11126,NaN,"11,126"
158,Montenegro,10227,9233,8274,Europe,10227
159,Liechtenstein,9442,"8,906 (2024)",8628,NaN,9442
160,Bermuda,NaN,"9,194 (2024)",8840,NaN,"9,194"
161,New Caledonia,NaN,"8,549 (2024)",8549,NaN,"8,549"
162,Barbados,8483,8017,7598,Americas,8483
163,Sierra Leone,8270,7464,6792,Africa,8270
164,Burundi,8137,3365,4431,Africa,8137
165,Maldives,8130,7741,7062,Asia,8130
166,Cayman Islands,NaN,"7,765 (2024)",7657,NaN,"7,765"
167,Isle of Man,NaN,"7,576 (2023)",NaN,NaN,"7,576"
168,Yemen,7435,"21,606 (2018)",14304,NaN,7435
169,Guam,NaN,"6,910 (2022)",NaN,NaN,"6,910"
170,Fiji,6352,6198,5968,Oceania,6352
171,French Polynesia,NaN,"6,324 (2024)",6323,NaN,"6,324"
172,South Sudan,6069,"11,998 (2015)",3522,NaN,6069
173,Suriname,5908,4524,4435,Americas,5908
174,Eswatini,5792,5161,4947,Africa,5792
175,Liberia,5642,5246,5251,Africa,5642
176,Andorra,4879,4501,4040,Europe,4879
177,Djibouti,4725,4625,4152,Africa,4725
178,U.S. Virgin Islands,NaN,"4,672 (2022)",NaN,NaN,"4,672"
179,Aruba,4671,"4,168 (2024)",4192,NaN,4671
180,Faroe Islands,NaN,"4,053 (2024)",NaN,NaN,"4,053"
181,Bhutan,3856,3579,3347,NaN,3856
182,Curaçao,NaN,"3,561 (2024)",3561,NaN,"3,561"
183,Central African Republic,3492,3066,2752,Africa,3492
184,Greenland,NaN,"3,327 (2023)",3466,NaN,"3,327"
185,Belize,3450,3327,3204,Americas,3450
186,Cape Verde,3448,3057,2768,Africa,3448
187,Guinea-Bissau,2985,2528,2008,Africa,2985
188,Lesotho,2972,2574,2391,Africa,2972
189,Gambia,2792,2594,2372,Africa,2792
190,Saint Lucia,2765,2656,2574,Americas,2765
191,Zanzibar,NaN,NaN,2530,NaN,2530
192,San Marino,2417,"2,027 (2023)",2082,NaN,2417
193,Antigua and Barbuda,2385,2338,2162,Americas,2385
194,Seychelles,2251,2387,2162,Africa,2251
195,Timor-Leste,2170,1902,1866,Asia,2170
196,Eritrea,"1,982 (2019)","2,065 (2011)",1917,NaN,"1,982"
197,Sint Maarten,NaN,1888,1670,NaN,1888
198,Solomon Islands,1836,1750,1584,Oceania,1836
199,British Virgin Islands,NaN,NaN,1830,NaN,1830
200,Comoros,1814,1815,1567,Africa,1814
201,Turks and Caicos Islands,NaN,"1,745 (2024)",1757,NaN,"1,745"
202,Grenada,1483,1420,1372,Americas,1483
203,Vanuatu,1396,1354,1092,Oceania,1396
204,Samoa,1376,1288,1253,Oceania,1376
205,Saint Vincent and the Grenadines,1236,1255,1136,Americas,1236
206,São Tomé and Príncipe,1161,981,828,Africa,1161
207,Saint Kitts and Nevis,1143,1184,1122,Americas,1143
208,Northern Mariana Islands,NaN,"1,096 (2022)",NaN,NaN,"1,096"
209,American Samoa,NaN,871 (2022),NaN,NaN,871
210,Dominica,791,724,689,Americas,791
211,Tonga,716,679,648,NaN,716
212,Saint Martin,NaN,649 (2021),NaN,NaN,649
213,Federated States of Micronesia,521,502,471,Oceania,521
214,Anguilla,NaN,NaN,456,NaN,456
215,Cook Islands,NaN,NaN,414,NaN,414
216,Kiribati,401,349,343,Oceania,401
217,Palau,377,345,310,NaN,377
218,Marshall Islands,342,308,281,Oceania,342
219,Nauru,196,176,187,Oceania,196
220,Montserrat,NaN,NaN,81,NaN,81
221,Tuvalu,65,57,56,Oceania,65